services:
  database:
    image: 'postgres:16'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: 'yourpassword'
      POSTGRES_USER: 'youruser'
      POSTGRES_DB: 'iworked'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'iworked']
    networks:
      - local_network
volumes:
  postgres_data: {}

networks:
  local_network:
