services:
  agent:
    image: ghcr.io/januarylabs/agentize:latest
    platform: linux/amd64
    environment:
      PORT: 3000
      PROJECT_SPEC: http://backend:3000/openapi.json
      PROJECT_API_URL: http://backend:3000
    env_file:
      - .env.agent
    ports:
      - '1420:3000'
    healthcheck:
      test: 'wget --no-verbose --spider --tries=1 http://localhost:3000/health || exit 1'
    networks:
      - app_network
    depends_on:
      migration:
        condition: service_completed_successfully
  migration:
    image: ghcr.io/januarylabs/agentize-migration:latest
    platform: linux/amd64
    env_file:
      - .env.agent
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fullstack
      args:
        VITE_AGENT_BASE_URL: http://localhost:1420
    env_file:
      - ./apps/backend/.env
    environment:
      AGENT_BASE_URL: http://agent:3000
    ports:
      - '1421:3000'
    healthcheck:
      test: 'wget --no-verbose --spider --tries=1 http://localhost:3000/health || exit 1'
    networks:
      - app_network
    depends_on:
      agent:
        condition: service_healthy
networks:
  app_network:

volumes:
  postgres_data: {}
