

app = 'iworked'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile.fullstack'

[env]
  PORT = '3000'
  HOSTNAME = "0.0.0.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size   = "shared-cpu-1x"
  memory = "256mb"
  cpu_kind = "shared"
  cpus      = 1
